#Warning: This file can contain server names, passwords, email addresses and other sensitive information.
#Wed Jun 10 03:01:11 GMT+02:00 2026
absolute_timeout=0
accuracy_before_logging=10
altitude_subtractgeoidheight=false
altitude_subtractoffset=0
annotations_buttons=
app_theme_setting=system
autoemail_enabled=false
autoemail_target=
autoftp_directory=GPSLogger
autoftp_enabled=false
autoftp_implicit=false
autoftp_password=
autoftp_port=21
autoftp_server=
autoftp_ssltls=
autoftp_useftps=false
autoftp_username=
autohttpfileupload_enabled=false
autoopengts_enabled=false
autoopengts_server_path=
autosend_enabled=true
autosend_frequency_minutes=60
autosend_frequency_whenstoppressed=true
autosend_sendzip=true
autosend_wifionly=false
current_profile_name=seeger_default
distance_before_logging=1
dropbox_enabled=false
google_drive_enabled=true
google_drive_folder_path=share_tab14/GPSLogger14
gpslogger_folder=/storage/emulated/0/gpslogger
hide_notification_buttons=true
hide_notification_from_lock_screen=true
hide_notification_from_status_bar=false
httpfileupload_basicauth_password=
httpfileupload_basicauth_username=
httpfileupload_body_type=form-data
httpfileupload_headers=
httpfileupload_method=POST
httpfileupload_url=
keep_fix=false
last_version_seen=1
latlong_display_format=DEGREES_MINUTES_SECONDS
log_customurl_basicauth_password=
log_customurl_basicauth_username=
log_customurl_body=
log_customurl_discard_offline_locations_enabled=false
log_customurl_enabled=false
log_customurl_headers=
log_customurl_method=GET
log_customurl_url=http\://localhost/log?lat\=%LAT&longitude\=%LON&time\=%TIME&s\=%SPD
log_geojson=true
log_gpx_11=false
log_gpx=true
log_kml=true
log_network_locations=false
log_nmea=false
log_opengts=false
log_passive_locations=true
log_plain_text_csv_decimal_comma=false
log_plain_text_csv_delimiter=,
log_plain_text=true
log_satellite_locations=false
new_file_creation=onceaday
new_file_custom_each_time=true
new_file_custom_keep_changing=true
new_file_custom_name=gpslogger
new_file_prefix_serial=false
only_log_if_significant_motion=false
opengts_accountname=
opengts_device_id=
opengts_server=
opengts_server_communication_method=HTTPS
opengts_server_port=443
osm_description=
osm_enabled=false
osm_promptfordetails_when_logging_starts=false
osm_tags=
osm_visibility=private
owncloud_directory=/gpslogger
owncloud_enabled=false
owncloud_password=
owncloud_server=
owncloud_username=
passive_filter_interval=1
retry_get_best_possible_accuracy=false
retry_time=60
significant_motion_bypass_interval=0
smtp_password=
smtp_port=25
smtp_server=
smtp_ssl=true
smtp_username=
startonapplaunch=false
startonbootup=true
stoponapplaunch=false
time_before_logging=1
useImperial=false
user_specified_locale=de
